name: flutter_chatgpt_sample
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.3 <3.0.0'

dependencies:
  dart_openai:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  riverpod_lint: ^1.1.2
  custom_lint: ^0.2.12
  riverpod_generator: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
